service: ldsc-webcam
frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'stage'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - Fn::Sub: arn:aws:s3:::${self:service}-${self:provider.stage}/incoming*

functions:
  tweet:
    handler: handler.tweet
    environment:
      TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY, ssm:/${self:service}/${self:provider.stage}/TWITTER_CONSUMER_KEY~false}
      TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET, ssm:/${self:service}/${self:provider.stage}/TWITTER_CONSUMER_SECRET~false}
      TWITTER_ACCESS_TOKEN_KEY: ${env:TWITTER_ACCESS_TOKEN_KEY, ssm:/${self:service}/${self:provider.stage}/TWITTER_ACCESS_TOKEN_KEY~false}
      TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET, ssm:/${self:service}/${self:provider.stage}/TWITTER_ACCESS_TOKEN_SECRET~false}
    events:
      - s3:
          bucket: ${self:service}-${self:provider.stage}
          event: s3:ObjectCreated:*
          rules:
            - prefix: "incoming/"

resources:
  Description: ${self:service} ${self:provider.stage}

plugins:
  - serverless-webpack
